server:
  port: 8090
spring:
  application:
    name: server-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wherebuy_new?serverTimezone=GMT
    username: root
    password: root
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/wei/mapper/*.xml
  type-aliases-package: classpath:com.wei.bo
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8080/eureka/ #服务注册的地址
  instance:
    prefer-ip-address: true
