server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/a410692241/CloudConfig.git     # ÅäÖÃgit²Ö¿âµÄµØÖ·
          username:                                              # git²Ö¿âµÄÕËºÅ
          password:                                              # git²Ö¿âµÄÃÜÂë
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/